### ISSUE TITLE
[sync function update] Sync data to smart contract

### ISSUE THREAD

**Issue by hackertron** [State-Channel-4/backend#15]
Have a look at https://github.com/State-Channel-4/backend/blob/main/controllers/contract.js#L17 and update the function with new smart contract. The function needs update related to sending data to smart contract in correct format. 

1. Check the contract at : https://github.com/State-Channel-4/contracts
2. mongodb schema : https://github.com/State-Channel-4/backend/blob/main/models/schema.js

**Comment by jp4g** [comment]
seems straight forward, will knock this out!

**Comment by jp4g** [comment]
Okay I had to spend some time getting familiar with code (added some training wheels - `populate.js` and a `docker-compose.yml` which will be removed before PR).  I couldn't find a previous version of the contract so I needed to get things running to decipher exact changes expected. 

The changes to be made:
 - `addUser` no longer exists in the contract and syncing does not need to consider new users
 - `addTag` should change to `createTagIfNotExists`
 - `addUrl` should change to `submitURL`
 
 Additionally, here are some things I've noticed about the smart contract/ backend
 - There are duplicates for getting url's submitted by users in [`getUserSubmittedURLs`](https://github.com/State-Channel-4/contracts/blob/main/contracts/UrlContract.sol#L165) and [`getURLsByUser`](https://github.com/State-Channel-4/contracts/blob/main/contracts/UrlContract.sol#L127). `getUserSubmittedURLs` should therefore be deleted.
  - [`User.submittedURLs`](https://github.com/State-Channel-4/contracts/blob/main/contracts/UrlContract.sol#L26) is only referenced in the user url getters mentioned above. in [`submitURL`](https://github.com/State-Channel-4/contracts/blob/main/contracts/UrlContract.sol#L51) there is no mutation of this storage. I didn't see a unit test and haven't tested myself but I am confident that the smart contract does not store the URL's submitted by a user. This can be quickly rectified by adding a line to push the url to `User.submittedURLs` in `submitURL`, but is also affected by the following issue.
  - [`submitURL`](https://github.com/State-Channel-4/contracts/blob/main/contracts/UrlContract.sol#L62) will use `msg.sender` as the url submitted. The function does not include a parameter for `submittedBy`. This parameter should be added to `submitURL` so that a user can be attributed to submitting a url.
  - There are likely gas savings that can be found in removing the use of arrays and instead using mappings that are stored incrementally (each mapping also needs a uint256 index to do so). This of course requires slightly more logic for the view functions
  - [`syncDataToSmartContract`](https://github.com/State-Channel-4/backend/blob/main/controllers/contract.js#L17) is missing the `(req, res)` syntax for express and hangs on requests. To fix, it needs to return an acceptable response from the function. I am adding that into this change fix
  - `createTagIfNoneExists` and `submitURL` should accept arrays of their params and allow batching. We can use `gasleft()` to ensure that batching does not produce a failing tx. This should have considerable gas savings and significantly decrease the stress of syncing the db where competitions for block space occur.
  - Instead of relying on the contract to check if a tag exists, the backend should first pull down all the tags and remove the tags that already exist. The check should stay in the solidity, but this will vastly cut down the redundant calls to the contract. edit: instead using `synced` on backend
  - The backend prevents duplicate URL's from being added, but the smart contract does not. Meanwhile, the contract prevents duplicate tags from being created, but the backend does not.
  - User has a "syncedToBlockchain" field in the schema that is not used.
  - contract syncing does not update tags or urls in the db to be synced. Fixing here
  
I'm going to go ahead and make the fix requested in this issue instead of continuing to read the contract for now, but perhaps I can write comprehensive unit testing (should be very quick) which will allow me to further investigate the integrity of the contract logic in the future!

**Comment by jp4g** [comment]
New goal: setup the syncing for the [uncensorable contract branch](https://github.com/State-Channel-4/contracts/tree/feat/uncensorable-contracts) using the same PR. Functionally outcome should be the same, but using the upcoming contract release instead of current master
